function T = dj_uncertainflashinference_v6_trialtable(bpodstruct, name)
% This function returns the trial table from a Bpod structure generated by
% the UncertainFlashInference_v6 protocol.
% 
% Maxime Maheu <maheu.mp@gmail.com> | 2025

% Same format as version #1
T = dj_uncertainflashinference_trialtable(bpodstruct, name);

end