function T = dj_uncertainflashinference_v4_summarytable(trialtable, cond)
% This function returns the summary table (day- or stage-specific) from the
% trial table generated by the dj_uncertainflashinference_v4_trialtable
% function.
% 
% Maxime Maheu <maheu.mp@gmail.com> | 2024

% Same format as version #1
T = dj_uncertainflashinference_summarytable(trialtable, cond);

end